### ISSUE TITLE
Peer-to-peer code review 18/05/23

### ISSUE THREAD

**Issue by deniodev** [musangamfure/LeaderBoard#4]
Hello @musangamfure ,
You did a great job 👏.

**Suggestion**
- Instead of passing POST requests multiple times. You can just post it once and call the method, as multiple requests might expire your API requests.

**Comment by musangamfure** [comment]
hello @deniodev, 

Thank you 🙌✔for your support.

![noted-note](https://github.com/musangamfure/LeaderBoard/assets/123179856/237d06ab-03ca-47b3-a173-78a6d4bb8391)

 Your suggestion is noted and going to implement it to improve my project.

cheers and Happy coding
